<?php

namespace Database\Seeders;

use App\Models\User;
use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;

class UserSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $usersData = [
            [
                'npk' => 'M231',
                'nama' => 'Arif superadmin',
                'password' => bcrypt('1234'),
                'no_telp' => '081329964278',
                'section_id' => '1',
                'department_id' => '1',
                'division_id' => '1',
                'role_id' => '1',
            ],
            [
                'npk' => 'A439',
                'nama' => 'Arif admin',
                'password' => bcrypt('1234'),
                'no_telp' => '081329964278',
                'section_id' => '1',
                'department_id' => '1',
                'division_id' => '1',
                'role_id' => '2',
            ],
            [
                'npk' => '8762',
                'nama' => 'Arif section',
                'password' => bcrypt('1234'),
                'no_telp' => '081329964278',
                'section_id' => '1',
                'department_id' => '1',
                'division_id' => '1',
                'role_id' => '3',
            ],
            [
                'npk' => '4278',
                'nama' => 'Arif department',
                'password' => bcrypt('1234'),
                'no_telp' => '081329964278',
                'section_id' => '1',
                'department_id' => '1',
                'division_id' => '1',
                'role_id' => '4',
            ],
            [
                'npk' => '0976',
                'nama' => 'Arif division',
                'password' => bcrypt('1234'),
                'no_telp' => '081329964278',
                'section_id' => '1',
                'department_id' => '1',
                'division_id' => '1',
                'role_id' => '5',
            ],
            [
                'npk' => 'T876',
                'nama' => 'Arif hrd',
                'password' => bcrypt('1234'),
                'no_telp' => '081329964278',
                'section_id' => '1',
                'department_id' => '1',
                'division_id' => '1',
                'role_id' => '6',
            ],
            // Karyawan Dept. Technical Support Baru
            [
                'npk' => '9920',
                'nama' => 'Eko sja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719290',
                'section_id' => '35',
                'department_id' => '13',
                'division_id' => '1',
            ],
            [
                'npk' => '9921',
                'nama' => 'Yusup saja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719291',
                'section_id' => '35',
                'department_id' => '13',
                'division_id' => '1',
            ],
            [
                'npk' => '9922',
                'nama' => 'Albar saja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719292',
                'section_id' => '35',
                'department_id' => '13',
                'division_id' => '1',
            ],
            [
                'npk' => '9923',
                'nama' => 'Seno saja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719293',
                'section_id' => '34',
                'department_id' => '13',
                'division_id' => '1',
            ],
            [
                'npk' => '9924',
                'nama' => 'Bayu saja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719294',
                'section_id' => '34',
                'department_id' => '13',
                'division_id' => '1',
            ],
            [
                'npk' => '9925',
                'nama' => 'Wira saja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719295',
                'section_id' => '34',
                'department_id' => '13',
                'division_id' => '1',
            ],
            [
                'npk' => '9926',
                'nama' => 'Tio saja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719296',
                'section_id' => '36',
                'department_id' => '13',
                'division_id' => '1',
            ],
            [
                'npk' => '9927',
                'nama' => 'Subagio saja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719297',
                'section_id' => '36',
                'department_id' => '13',
                'division_id' => '1',
            ],
            [
                'npk' => '9928',
                'nama' => 'Samsul saja',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719298',
                'section_id' => '36',
                'department_id' => '13',
                'division_id' => '1',
            ],

            // Admin
            [
                'npk' => 'adminPE',
                'nama' => 'admin plant engineering',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719112',
                'section_id' => '36',
                'department_id' => '13',
                'division_id' => '1',
                'role_id' => '2',
            ],
            [
                'npk' => 'adminDigi',
                'nama' => 'admin Digitalisasi',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719121',
                'section_id' => '35',
                'department_id' => '13',
                'division_id' => '1',
                'role_id' => '2',
            ],
            [
                'npk' => 'adminAuto',
                'nama' => 'admin Automasi',
                'password' => bcrypt('1234'),
                'no_telp' => '08267719211',
                'section_id' => '34',
                'department_id' => '13',
                'division_id' => '1',
                'role_id' => '2',
            ],

            // Section
            [
                'npk' => 'sectionPE',
                'nama' => 'section plant engineering',
                'password' => bcrypt('1234'),
                'no_telp' => '08267718112',
                'section_id' => '36',
                'department_id' => '13',
                'division_id' => '1',
                'role_id' => '3',
            ],
            [
                'npk' => 'sectionDigi',
                'nama' => 'admin Digitalisasi',
                'password' => bcrypt('1234'),
                'no_telp' => '08267718121',
                'section_id' => '35',
                'department_id' => '13',
                'division_id' => '1',
                'role_id' => '3',
            ],
            [
                'npk' => 'sectionAuto',
                'nama' => 'section Automasi',
                'password' => bcrypt('1234'),
                'no_telp' => '08267718211',
                'section_id' => '34',
                'department_id' => '13',
                'division_id' => '1',
                'role_id' => '3',
            ],

            // Karyawan Dept. Production
            [
                'npk' => '8920',
                'nama' => 'priam sitohang',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788290',
                'section_id' => '30',
                'department_id' => '2',
                'division_id' => '1',
            ],
            [
                'npk' => '8921',
                'nama' => 'alex mansur',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788291',
                'section_id' => '30',
                'department_id' => '2',
                'division_id' => '1',
            ],
            [
                'npk' => '8922',
                'nama' => 'jaka sitombul',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788292',
                'section_id' => '30',
                'department_id' => '2',
                'division_id' => '1',
            ],
            [
                'npk' => '8923',
                'nama' => 'Dio amandio',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788293',
                'section_id' => '30',
                'department_id' => '2',
                'division_id' => '1',
            ],
            [
                'npk' => '8924',
                'nama' => 'Rian Barbarian',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788294',
                'section_id' => '29',
                'department_id' => '2',
                'division_id' => '1',
            ],
            [
                'npk' => '8925',
                'nama' => 'Sidiq waseso',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788295',
                'section_id' => '29',
                'department_id' => '2',
                'division_id' => '1',
            ],
            [
                'npk' => '8926',
                'nama' => 'Doughlas muto',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788296',
                'section_id' => '29',
                'department_id' => '2',
                'division_id' => '1',
            ],
            [
                'npk' => '8927',
                'nama' => 'moena sitaluang',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788297',
                'section_id' => '29',
                'department_id' => '2',
                'division_id' => '1',
            ],
            [
                'npk' => '8928',
                'nama' => 'zeremia silalabung',
                'password' => bcrypt('1234'),
                'no_telp' => '08267788298',
                'section_id' => '29',
                'department_id' => '2',
                'division_id' => '1',
            ],
            ['npk' => '0014', 'nama' => 'Isthof Fathony', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '3', 'department_id' => '2', 'division_id' => '1'],
            ['npk' => '0012', 'nama' => 'Stanislaus Kostha Putro Eko Kurniawan', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '2', 'department_id' => '2', 'division_id' => '1'],
            ['npk' => '1660', 'nama' => 'Sri Sulistiawati Kusuma', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '3', 'department_id' => '2', 'division_id' => '1'],
            ['npk' => '1662', 'nama' => 'Gandi Mufid', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '3', 'department_id' => '2', 'division_id' => '1'],
            ['npk' => '1663', 'nama' => 'Khalid', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '2', 'department_id' => '2', 'division_id' => '1'],
            ['npk' => '1665', 'nama' => 'Yusuf', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '3', 'department_id' => '2', 'division_id' => '1'],
            ['npk' => '1667', 'nama' => 'Harris', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '2', 'department_id' => '2', 'division_id' => '1'],
            ['npk' => '0013', 'nama' => 'Gita Apriani', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '1', 'department_id' => '1', 'division_id' => '1'],
            ['npk' => '0011', 'nama' => 'Ahmad Fathoni', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '1', 'department_id' => '1', 'division_id' => '1'],
            ['npk' => '1666', 'nama' => 'Lia', 'password' => bcrypt('1234'), 'no_telp' => '081329964278', 'section_id' => '1', 'department_id' => '1', 'division_id' => '1'],
            ['npk' => '0015', 'nama' => 'Rudi Hartono', 'password' => bcrypt('1234'), 'no_telp' => '081329964279', 'section_id' => '4', 'department_id' => '3', 'division_id' => '1'],
            ['npk' => '0016', 'nama' => 'Maya Purnama', 'password' => bcrypt('1234'), 'no_telp' => '081329964280', 'section_id' => '4', 'department_id' => '3', 'division_id' => '1'],
            ['npk' => '0017', 'nama' => 'Diana Sari', 'password' => bcrypt('1234'), 'no_telp' => '081329964281', 'section_id' => '5', 'department_id' => '4', 'division_id' => '1'],
            ['npk' => '0018', 'nama' => 'Agus Santoso', 'password' => bcrypt('1234'), 'no_telp' => '081329964282', 'section_id' => '5', 'department_id' => '4', 'division_id' => '1'],
            ['npk' => '0019', 'nama' => 'Dewi Lestari', 'password' => bcrypt('1234'), 'no_telp' => '081329964283', 'section_id' => '6', 'department_id' => '5', 'division_id' => '1'],
            ['npk' => '0020', 'nama' => 'Siti Fatimah', 'password' => bcrypt('1234'), 'no_telp' => '081329964284', 'section_id' => '6', 'department_id' => '5', 'division_id' => '1'],
            ['npk' => '0021', 'nama' => 'Eka Putri', 'password' => bcrypt('1234'), 'no_telp' => '081329964285', 'section_id' => '6', 'department_id' => '5', 'division_id' => '1'],
            ['npk' => '0022', 'nama' => 'Sukma Ayu', 'password' => bcrypt('1234'), 'no_telp' => '081329964286', 'section_id' => '7', 'department_id' => '6', 'division_id' => '1'],
            ['npk' => '0023', 'nama' => 'Rizky Aditya', 'password' => bcrypt('1234'), 'no_telp' => '081329964287', 'section_id' => '7', 'department_id' => '6', 'division_id' => '1'],
            ['npk' => '0024', 'nama' => 'Fanny Rahayu', 'password' => bcrypt('1234'), 'no_telp' => '081329964288', 'section_id' => '8', 'department_id' => '7', 'division_id' => '1'],
            ['npk' => '0025', 'nama' => 'Widi Astuti', 'password' => bcrypt('1234'), 'no_telp' => '081329964289', 'section_id' => '8', 'department_id' => '7', 'division_id' => '1'],
            ['npk' => '0026', 'nama' => 'Alvin Riyanto', 'password' => bcrypt('1234'), 'no_telp' => '081329964290', 'section_id' => '8', 'department_id' => '7', 'division_id' => '1'],
            ['npk' => '0027', 'nama' => 'Cindy Lestari', 'password' => bcrypt('1234'), 'no_telp' => '081329964291', 'section_id' => '9', 'department_id' => '8', 'division_id' => '1'],
            ['npk' => '0028', 'nama' => 'Irfan Maulana', 'password' => bcrypt('1234'), 'no_telp' => '081329964292', 'section_id' => '9', 'department_id' => '8', 'division_id' => '1'],
            ['npk' => '0029', 'nama' => 'Rina Dewi', 'password' => bcrypt('1234'), 'no_telp' => '081329964293', 'section_id' => '10', 'department_id' => '9', 'division_id' => '1'],
            ['npk' => '0030', 'nama' => 'Fahri Rizal', 'password' => bcrypt('1234'), 'no_telp' => '081329964294', 'section_id' => '10', 'department_id' => '9', 'division_id' => '1'],
            ['npk' => '0031', 'nama' => 'Dinda Shofia', 'password' => bcrypt('1234'), 'no_telp' => '081329964295', 'section_id' => '10', 'department_id' => '9', 'division_id' => '1'],
            ['npk' => '0032', 'nama' => 'Budi Santoso', 'password' => bcrypt('1234'), 'no_telp' => '081329964296', 'section_id' => '11', 'department_id' => '10', 'division_id' => '1'],
            ['npk' => '0033', 'nama' => 'Nina Agustina', 'password' => bcrypt('1234'), 'no_telp' => '081329964297', 'section_id' => '11', 'department_id' => '10', 'division_id' => '1'],
            ['npk' => '0034', 'nama' => 'Julius', 'password' => bcrypt('1234'), 'no_telp' => '081329964298', 'section_id' => '11', 'department_id' => '10', 'division_id' => '1'],
            ['npk' => '0035', 'nama' => 'Sari Meilani', 'password' => bcrypt('1234'), 'no_telp' => '081329964299', 'section_id' => '12', 'department_id' => '11', 'division_id' => '1'],
            ['npk' => '0036', 'nama' => 'Hendra Wijaya', 'password' => bcrypt('1234'), 'no_telp' => '081329964300', 'section_id' => '12', 'department_id' => '11', 'division_id' => '1'],
            ['npk' => '0037', 'nama' => 'Lina Kartika', 'password' => bcrypt('1234'), 'no_telp' => '081329964301', 'section_id' => '12', 'department_id' => '11', 'division_id' => '1'],
            ['npk' => '0038', 'nama' => 'Rizky Pradana', 'password' => bcrypt('1234'), 'no_telp' => '081329964302', 'section_id' => '13', 'department_id' => '12', 'division_id' => '1'],
            ['npk' => '0039', 'nama' => 'Citra Indah', 'password' => bcrypt('1234'), 'no_telp' => '081329964303', 'section_id' => '13', 'department_id' => '12', 'division_id' => '1'],
            ['npk' => '0040', 'nama' => 'Rudi Kurniawan', 'password' => bcrypt('1234'), 'no_telp' => '081329964304', 'section_id' => '14', 'department_id' => '13', 'division_id' => '1'],
            ['npk' => '0041', 'nama' => 'Rina Lestari', 'password' => bcrypt('1234'), 'no_telp' => '081329964305', 'section_id' => '14', 'department_id' => '13', 'division_id' => '1'],
            ['npk' => '0042', 'nama' => 'Andi Setiawan', 'password' => bcrypt('1234'), 'no_telp' => '081329964306', 'section_id' => '14', 'department_id' => '13', 'division_id' => '1'],
            ['npk' => '0043', 'nama' => 'Siti Khadijah', 'password' => bcrypt('1234'), 'no_telp' => '081329964307', 'section_id' => '15', 'department_id' => '14', 'division_id' => '1'],
            ['npk' => '0044', 'nama' => 'Agung Prabowo', 'password' => bcrypt('1234'), 'no_telp' => '081329964308', 'section_id' => '15', 'department_id' => '14', 'division_id' => '1'],
            ['npk' => '0045', 'nama' => 'Nadia Aminah', 'password' => bcrypt('1234'), 'no_telp' => '081329964309', 'section_id' => '15', 'department_id' => '14', 'division_id' => '1'],
            ['npk' => '0046', 'nama' => 'Ilham Hidayat', 'password' => bcrypt('1234'), 'no_telp' => '081329964310', 'section_id' => '16', 'department_id' => '15', 'division_id' => '1'],
            ['npk' => '0047', 'nama' => 'Rani Maulida', 'password' => bcrypt('1234'), 'no_telp' => '081329964311', 'section_id' => '16', 'department_id' => '15', 'division_id' => '1'],
            ['npk' => '0048', 'nama' => 'Fitria Rizki', 'password' => bcrypt('1234'), 'no_telp' => '081329964312', 'section_id' => '16', 'department_id' => '15', 'division_id' => '1'],
            ['npk' => '0049', 'nama' => 'Arief Prabowo', 'password' => bcrypt('1234'), 'no_telp' => '081329964313', 'section_id' => '17', 'department_id' => '16', 'division_id' => '1'],
            ['npk' => '0050', 'nama' => 'Dewi Ningsih', 'password' => bcrypt('1234'), 'no_telp' => '081329964314', 'section_id' => '17', 'department_id' => '16', 'division_id' => '1'],
        ];
        foreach ($usersData as $key => $val) {
            User::create($val);
        }
    }
}
